Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,55 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  rapid-api-script:
-    runs-on: windows-latest
-    strategy:
-      matrix:
-        script:
-          - "rapid_API.py"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.10'
-
-      - name: Cache Python dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Set Python UTF-8 Encoding
-        run: echo "PYTHONIOENCODING=UTF-8" >> $GITHUB_ENV
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          if (Test-Path requirements.txt) { pip install -r requirements.txt }
-          python -m pip install nest_asyncio
-        shell: powershell
-
-      - name: Install Firefox and Geckodriver
-        run: |
-          choco install firefox -y
-          $response = Invoke-WebRequest -Uri "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | ConvertFrom-Json
-          $GECKO_VERSION = $response.tag_name -replace "v", ""
-          $GECKO_URL = "https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-win64.zip"
-          Invoke-WebRequest -Uri $GECKO_URL -OutFile geckodriver.zip
-          Expand-Archive geckodriver.zip -DestinationPath C:\GeckoDriver
-          $env:PATH += ";C:\GeckoDriver"
-          C:\GeckoDriver\geckodriver.exe --version
-        shell: powershell
-
-      - name: Run Python script
-        run: python "${{ matrix.script }}"
-
-  run-script-1:
+  run-script:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -79,10 +31,14 @@ jobs:
           sudo mv geckodriver /usr/local/bin/
           geckodriver --version
 
+      - name: Set up Google Credentials
+        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS_JSON }}" >> $GITHUB_ENV
+
+      - name: Verify credentials existence
+        run: cat $GOOGLE_APPLICATION_CREDENTIALS || echo "Credential file missing!"
+
       - name: Verify script location
         run: ls -R
 
       - name: Run Python script
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
         run: python "Skip Tracing/truppl_parser.py"
